[package]
name = "webdavrs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Lorenzo Carbonell <lorenzo.carbonell.cerezo@gmail.com>"]
rust-version = "1.76"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5", features = ["runtime-actix-rustls", "sqlite", "macros", "offline", "chrono"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.9"
log = "0.4"
actix-rt = "2.7"
tokio = { version = "1.21", features = ["full"]}
dav-server = { version = "0.5", features = ["actix-compat"]}
openssl = { version = "0.10", features = ["vendored"] }
tera = "1.17"
http = "0.2"
md5 = "0.7"
derive_more = "0.99"
axum-auth = "0.7.0"
axum = { version = "0.7.4", features = ["multipart"] }
axum-extra = { version = "0.9.2", features = ["cookie"] }
minijinja = { version = "1.0.12", features = ["loader"] }
tower-http = { version = "0.5.1", features = ["trace", "fs", "cors"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["local-time", "env-filter"] }
once_cell = "1.19.0"
