port: 9090
directory: /share
users:
  - name: user1
    hashed_password: "25d55ad283aa400af464c76d713c07ad"
    active: true
  - name: user2
    hashed_password: "25d55ad283aa400af464c76d713c07ad"
    active: true


