port: 9090
directory: /share
workers: 4
users:
  - name: user1
    hashed_password: ":$2y$10$R5PeUvhiPciZA2NsBuky0eS/LKCQ0kMHxrOBpuABeikRA8VRVOOIi"
    active: true
  - name: user2
    hashed_password: ":$2y$10$QQg//X8./ENAZS7EUWjHrehvbNOm9jbIaltd4wf92WXh8i4PvEhIO"
    active: true


