port: 9090
directory: /share
workers: 4
users:
  - name: user1
    hashed_password: '$2y$12$foIrZBsGcEq09HzNSKGaAOYuOcAFl23tfXyDaYdUL/wt0ug.UGlbO'
    active: true
  - name: user2
    hashed_password: '$2y$12$7ZGW1LGiV/UKLpElwJx20OzpF8dxd4deUAvcqoMM1UinuRAX6o8oS'
    active: true


